services:
  api:
    image: js-26-team-2-esdp-api
    build:
      context: api
      dockerfile: Dockerfile
      network: host
    ports:
      - 8000:8000
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - ORIGIN=${WEB_HOST}
      - MONGO_HOST=db
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    depends_on:
      db:
        condition: service_started
    networks:
      - backend

  db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - 27017:27017
    networks:
      - backend

  web:
    image: js-26-team-2-esdp-front
    build:
      context: frontend
      dockerfile: Dockerfile
      network: host
    ports:
      - 80:80
    depends_on:
      api:
        condition: service_started

networks:
  backend:
    driver: bridge
