on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          path: /src

      - name: Install keys
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_DEPLOYMENT_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Copy project source to the remote
        run: |
          scp -r /src ${{ secrets.PRINCIPAL }}@${{ secrets.HOST }}:/src

      - name: Build project on the remote
        run: |
          ssh ${{ secrets.PRINCIPAL }}@${{ secrets.HOST }} \
            cd /src && \
            docker compose build
        env:
          API_HOST: ${{ secrets.HOST }}

      - name: Delete project source from the remote
        run: |
          ssh ${{ secrets.PRINCIPAL }}@${{ secrets.HOST }} \
            rm -rf /src/!(docker-compose.yaml)
                   
      - name: Start project on the remote
        run: |
          ssh ${{ secrets.PRINCIPAL }}@${{ secrets.HOST }} \
            cd /src && \
            docker compose up
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          WEB_HOST: ${{ secrets.HOST }}
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
