name: Deploy to DigitalOcean droplet

on:
  pull_request:
    branches:
      - main
    types:
      - closed

env:
  HOST: ${{ secrets.HOST }}
  PRINCIPAL: ${{ secrets.PRINCIPAL }}

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install keys
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_DEPLOYMENT_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Create remote docker context
        run: docker context create remote --docker "host=ssh://${{ env.PRINCIPAL }}@${{ env.HOST }}"

      - name: Stop project on remote
        run: docker --context remote compose down

      - name: Build project on remote
        run: docker --context remote compose build --build-arg API_HOST=${{ env.HOST }}

      - name: Start project on remote
        run: docker --context remote compose up --detach
        env:
          WEB_HOST: ${{ env.HOST }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
